#!/bin/bash
# Written by Heiko Horn 2018.03.14
# will return the Password change interval from dsconfigad

RESULT=$(dsconfigad -show | grep "Password change interval" | sed 's/Password change interval       = //g' | sed 's/ //g')
echo "<result>$RESULT</result>"

exit 0
